const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const legacy=fs.readFileSync(path.join(root,'legacy-v24.html'),'utf8');
const management=fs.readFileSync(path.join(root,'legacy-management-v28.js'),'utf8');
assert(index.includes('./legacy-v24.html?v=20260915-v28'),'default entry must keep original app as main');
assert(index.includes('legacy-management-v28.js?v=20260915-v28'),'management extension must be injected into original app');
assert(legacy.includes("const TABS=[['cal','식단','cal'],['shop','장보기','shop']"),'original bottom navigation source must remain preserved');
assert(management.includes("TABS[1][1]='관리'"),'shopping tab must be renamed to management at runtime');
assert(management.includes('1단계 · 재고관리'),'management needs inventory stage');
assert(management.includes('2단계 · 장보기'),'management needs shopping stage');
assert(management.includes('3단계 · 식단만들기'),'management needs prep stage');
assert(management.includes('4단계 · 전체 스케줄 보기'),'main schedule must remain the original meal tab');
console.log('PASS: original app preserved, management-only extension wired');